<?php
//Skins
$skins_options = array(
			'default' => array(
					'options' => "a:12:{s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:17:\"header-custom-258\";s:9:\"copyright\";s:132:\"<a href=\"https://themeforest.net/user/themerex/portfolio\" target=\"_blank\" rel=\"noopener\">ThemeREX</a> © {{Y}}. All Rights Reserved.\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"header_type\";s:6:\"custom\";s:18:\"show_related_posts\";s:1:\"0\";s:13:\"counters_post\";s:26:\"views=0|likes=0|comments=1\";s:10:\"meta_parts\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:15:\"meta_parts_post\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:20:\"theme_style_switcher\";s:1:\"1\";s:18:\"nav_menu_locations\";a:1:{s:9:\"menu_main\";i:0;}}"
				),
		'dietitian' => array(
					'options' => "a:13:{s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:17:\"header-custom-258\";s:9:\"copyright\";s:132:\"<a href=\"https://themeforest.net/user/themerex/portfolio\" target=\"_blank\" rel=\"noopener\">ThemeREX</a> © {{Y}}. All Rights Reserved.\";s:16:\"body_style_front\";s:7:\"inherit\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"header_type\";s:6:\"custom\";s:18:\"show_related_posts\";s:1:\"0\";s:13:\"counters_post\";s:26:\"views=0|likes=0|comments=1\";s:10:\"meta_parts\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:15:\"meta_parts_post\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:20:\"theme_style_switcher\";s:1:\"1\";s:18:\"nav_menu_locations\";a:1:{s:9:\"menu_main\";i:0;}}"
				),
		'financial-adviser' => array(
					'options' => "a:13:{s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:17:\"header-custom-258\";s:9:\"copyright\";s:132:\"<a href=\"https://themeforest.net/user/themerex/portfolio\" target=\"_blank\" rel=\"noopener\">ThemeREX</a> © {{Y}}. All Rights Reserved.\";s:16:\"body_style_front\";s:7:\"inherit\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"header_type\";s:6:\"custom\";s:18:\"show_related_posts\";s:1:\"0\";s:13:\"counters_post\";s:26:\"views=0|likes=0|comments=1\";s:10:\"meta_parts\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:15:\"meta_parts_post\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:20:\"theme_style_switcher\";s:1:\"1\";s:18:\"nav_menu_locations\";a:1:{s:9:\"menu_main\";i:0;}}"
                 ),
        'law' => array(
            'options' => "a:13:{s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:17:\"header-custom-258\";s:9:\"copyright\";s:132:\"<a href=\"https://themeforest.net/user/themerex/portfolio\" target=\"_blank\" rel=\"noopener\">ThemeREX</a> © {{Y}}. All Rights Reserved.\";s:16:\"body_style_front\";s:7:\"inherit\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"header_type\";s:6:\"custom\";s:18:\"show_related_posts\";s:1:\"0\";s:13:\"counters_post\";s:26:\"views=0|likes=0|comments=1\";s:10:\"meta_parts\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:15:\"meta_parts_post\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:20:\"theme_style_switcher\";s:1:\"1\";s:18:\"nav_menu_locations\";a:1:{s:9:\"menu_main\";i:0;}}"
        ),
		'real-estate' => array(
					'options' => "a:13:{s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:17:\"header-custom-258\";s:9:\"copyright\";s:132:\"<a href=\"https://themeforest.net/user/themerex/portfolio\" target=\"_blank\" rel=\"noopener\">ThemeREX</a> © {{Y}}. All Rights Reserved.\";s:16:\"body_style_front\";s:7:\"inherit\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"header_type\";s:6:\"custom\";s:18:\"show_related_posts\";s:1:\"0\";s:13:\"counters_post\";s:26:\"views=0|likes=0|comments=1\";s:10:\"meta_parts\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:15:\"meta_parts_post\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:20:\"theme_style_switcher\";s:1:\"1\";s:18:\"nav_menu_locations\";a:1:{s:9:\"menu_main\";i:0;}}"
				),
		'photographer' => array(
					'options' => "a:13:{s:18:\"custom_css_post_id\";i:-1;s:12:\"header_style\";s:17:\"header-custom-258\";s:9:\"copyright\";s:132:\"<a href=\"https://themeforest.net/user/themerex/portfolio\" target=\"_blank\" rel=\"noopener\">ThemeREX</a> © {{Y}}. All Rights Reserved.\";s:16:\"body_style_front\";s:7:\"inherit\";s:19:\"load_fonts-4-family\";s:7:\"inherit\";s:19:\"load_fonts-5-family\";s:7:\"inherit\";s:11:\"header_type\";s:6:\"custom\";s:18:\"show_related_posts\";s:1:\"0\";s:13:\"counters_post\";s:26:\"views=0|likes=0|comments=1\";s:10:\"meta_parts\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:15:\"meta_parts_post\";s:61:\"date=1|author=1|counters=1|categories=1|tags=1|share=0|edit=0\";s:20:\"theme_style_switcher\";s:1:\"1\";s:18:\"nav_menu_locations\";a:1:{s:9:\"menu_main\";i:0;}}"
				)
		);
?>